source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'MinterExplorer_Example' do
	pod 'MinterCore'
	pod 'MinterExplorer', :path => '../'
	

  target 'MinterExplorer_Tests' do
    inherit! :search_paths
		pod 'MinterCore'
		pod 'MinterExplorer', :path => '../'
		pod 'Quick', '~> 1.2.0'
		pod 'Nimble', '~> 7.0.2'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if ['Nimble'].include? target.name
			target.build_configurations.each do |config|
				config.build_settings['SWIFT_VERSION'] = '3.2'
			end
		end
	end
end
